// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIZcVd8fnujLe5X6gwARWWeyOvh4HlUtw',
    appId: '1:951801974864:web:c3de49dcf30d98fe21c155',
    messagingSenderId: '951801974864',
    projectId: 'recipe-pro-606a6',
    authDomain: 'recipe-pro-606a6.firebaseapp.com',
    storageBucket: 'recipe-pro-606a6.firebasestorage.app',
    measurementId: 'G-2STCSMR293',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN8ZNErtSK8Aw-8jlp9IJkGv3YgjAY1bQ',
    appId: '1:951801974864:android:a8045989779725a921c155',
    messagingSenderId: '951801974864',
    projectId: 'recipe-pro-606a6',
    storageBucket: 'recipe-pro-606a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLFMUBpmlqT27af_pZmoITTig7FTMIeLs',
    appId: '1:951801974864:ios:04ab4636d03e846d21c155',
    messagingSenderId: '951801974864',
    projectId: 'recipe-pro-606a6',
    storageBucket: 'recipe-pro-606a6.firebasestorage.app',
    iosBundleId: 'com.example.recipePro',
  );
}
